### PR TITLE
gym-membership-reg-app

### PR DESCRIPTION
**Pull request by Marvelous-O**
> By submitting this pull request, you agree to the [contribution guidelines](https://github.com/pnp/powerplatform-samples/blob/main/CONTRIBUTING.md)

> If you aren't familiar with how to contribute to open-source repositories using GitHub, or if you find the instructions on this page confusing, sign up for one of our [Sharing is Caring](https://pnp.github.io/sharing-is-caring/#pnp-sic-events) events. It's completely free, and we'll guide you through the process.

> To submit a pull request with multiple authors, make sure that at least one commit is a co-authored commit by adding a `Co-authored-by:` trailer to the commit's message. E.g.: `Co-authored-by: name <name@example.com>`

> Put an `x` in all the items that apply (`[x]`, without spaces), make notes next to any that haven't been addressed.

- [ ] Bug fix?
- [x] New sample?
- [ ] Related issues: fixes #X, partially #Y, mentioned in #Z
- [ ] Needs API permissions?
- [ ] Has other prerequisites? (E.g. requires a list, document library, etc.)

## What's in this Pull Request?

> First Sample Submission.
>

## Checklist

- [ ] My pull request affects only ONE sample.
- [x] I have updated the README file.
- [x] My README has at least one static high-resolution screenshot (i.e. not a GIF)
- [ ] My README contains complete setup instructions, including pre-requisites and permissions required

### CODE REVIEW

**Comment by Katerina-Chernevskaya** [comment]
Hi @Marvelous-O,

Thank you for your sample!
When I tried to import the solution, I got an error related to Missing Dependencies:
image
Could you please check that all components of the solution are in place?

Also please rename the folder to keep only lower case. And please review the installation guide - if your solution required a SharePoint site or library, please specify prerequisites for this (what should be created in advance).

Thank you!

**Review by Marvelous-O — COMMENTED** [review]
@Katerina-Chernevskaya  Made Changes, please verify

**Comment by Katerina-Chernevskaya** [comment]
Hi @Marvelous-O ,

The error with missing dependencies still reproduced. Could you please check once again, especially connection references?

Thank you!

**Comment by Marvelous-O** [comment]
Hi @Katerina-Chernevskaya,  Made Changes, please verify. Thank you

**Pull request closed without merging**
