### PR TITLE
Chat Canvas App Template

### PR DESCRIPTION
**Pull request by shaheerahmadch**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                           |
| New feature?    | no                                |
| New sample?     | yes                               |
| Related issues? | fnone|

## Solution Details

|        Q                                                  |                    A                    |
| --------------------------------------------------------- | --------------------------------------- |
| Solution requires premium license                         | no                              |
| Solution uses experimental features (see [licensing guidelines](https://go.microsoft.com/fwlink/?linkid=2085130)) | no   |
| Which connectors are used?                                |  DataVerse |
| Solution uses on-premises connectors?                     | no                                |
| Solution uses custom connectors?                          | no                               |
| Layout                                                    | Responsive                              |

## What's in this Pull Request?

Been working on this for quite a while now. This Canvas application is inspired by WhatsApp.
Features include:
✉️ Send messages seamlessly to system users
🎙️ Share voice notes effortlessly
📱 Enjoy a user-friendly, responsive design
🌐 Stay connected with ease, anytime, anywhere
Screenshot 2023-09-02 130516

### CODE REVIEW

**Comment by shaheerahmadch** [comment]
@Katerina-Chernevskaya thanks for your guidance. this pull request contains the source code generated using the instructions you provided,

**Comment by shaheerahmadch** [comment]
It's been over two weeks since my submission, Is there a problem that i can fix?
Thanks

**Comment by shaheerahmadch** [comment]
@Katerina-Chernevskaya the gear icon is not supposed to perform anything. Its Just there if the user wants to add any settings. They would know that the gear icon should be placed here. Its responsive...

**Comment by shaheerahmadch** [comment]
@Katerina-Chernevskaya I've updated the readme.

**Review by Katerina-Chernevskaya — APPROVED** [review]
Thank you for your contribution! I've made several changes in README file and regenerated the solution from the provided source code.
Thank you for your effort and submission!

**Pull request merged**
