### PR TITLE
Incident Reporting

### PR DESCRIPTION
**Pull request by shaheerahmadch**
- [ ] Bug fix?
- [x ] New sample?
- [ ] Related issues: fixes #X, partially #Y, mentioned in #Z
- [ ] Needs API permissions?
- [ x] Has other prerequisites? (Requires a sharepoint site & list.)

## What's in this Pull Request?

> The Incident Reporting Canvas Application is a powerful tool designed to streamline incident reporting and enhance data collection. With its unique and visually appealing phone layout UI/UX, this application provides an efficient and user-friendly solution for reporting and managing incidents. Seamlessly integrated with SharePoint, it allows users to upload incident images and related data securely.

image
image

## Checklist

- [ x] My pull request affects only ONE sample.
- [x ] I have updated the README file.
- [x ] My README has at least one static high-resolution screenshot (i.e. not a GIF)
- [ x] My README contains complete setup instructions, including pre-requisites and permissions required

### CODE REVIEW

**Comment by shaheerahmadch** [comment]
@Katerina-Chernevskaya oppened a new pull request after going through your instructions. Hope this is okay.

**Comment by shaheerahmadch** [comment]
Any update?
-
@aprildunnam  @Warner-Digital @PopWarner

**Comment by shaheerahmadch** [comment]
@hugoabernier Is there an issue with my submissions?

**Comment by shaheerahmadch** [comment]
It's been over two weeks since my submission, Is there a problem that i can fix?
Thanks

**Comment by shaheerahmadch** [comment]
@Katerina-Chernevskaya 
Can you please take a look at this one? I'm sure you wont encounter any issues in this one. It's according to the latest documentations.
Also, I apologize for causing so much inconvenience in the previous pull requests. I'm new at this. I'm learning along the way. Learnt so much from you guys. 
Thanks a lot.

**Comment by Katerina-Chernevskaya** [comment]
Hi @shaheerahmadch,
I'm working on this pull request. I built the solution zip file based on the provided source code. So far so good here.
But when I tried to import the solution I was blocked due to the error: Some dependencies are missing. This is the log:
`[{"SolutionValidationResultType":"Error","Message":"The following solution cannot be imported: IncidentReporting. Some dependencies are missing. The missing dependencies are : <MissingDependencies><MissingDependency><Required type=\"1\" schemaName=\"deploymentstagerun\" displayName=\"Deployment Stage Run\" solution=\"msdyn_AppDeploymentMetadata (9.1.1.8)\"><package>msdyn_AppDeploymentAnchor (9.1.1.8)</package></Required><Dependent type=\"1\" schemaName=\"systemuser\" displayName=\"Employee\" /></MissingDependency><MissingDependency><Required type=\"1\" schemaName=\"msfp_survey\" displayName=\"Customer Voice survey\" solution=\"MicrosoftFormsPro (2.0.0.43)\"><package>MicrosoftFormsPro (2.0.0.43)</package></Required><Dependent type=\"1\" schemaName=\"systemuser\" displayName=\"Employee\" /></MissingDependency></MissingDependencies> , ProductUpdatesOnly : False","ErrorCode":-2147188707,"AdditionalInfo":null}]`

Could you please check and update the source code to fix this issue? Also please make sure to update your branch to reflect the lates changes from the main branch.

Thank you!

**Comment by shaheerahmadch** [comment]
I validated this one before pulling the request. No worries I'll check again. Thanks for the update. Appreciate your time.

**Comment by shaheerahmadch** [comment]
I have fixed the dependency issue and successfully imported it into a new trial environment. I have updated the source code as well as the solutions in the pull request. You should be able to deploy the solution now. Thanks alot

image

**Comment by shaheerahmadch** [comment]
@Katerina-Chernevskaya Thanks for your time

**Review by Katerina-Chernevskaya — APPROVED** [review]
Thank you for the source code update @shaheerahmadch ! The solution has now been successfully built, imported, and run, and I can proceed with the merge.

Here are a few minor suggestions for future improvements:
1) Before exporting the solution or creating the source code, I recommend removing the Current Value from the solution. This will allow users to set up values for the environment variables during import, which is a more straightforward approach.
2) Please review the connection to the SharePoint list. It appears you are connecting to the 'Incident Images' site, while the prerequisites guide users to create an 'IncidentReports' list. This discrepancy has resulted in an issue where users are unable to upload images.

Upon rectifying this, feel free to submit a new pull request to update your solution.

Thank you for your time and contribution!

Regards,
Katerina Chernevskaya

**Comment by shaheerahmadch** [comment]
Thanks for the suggestions. I'm working on another sample that utilizes SharePoint. I'll make sure to keep your suggestions in mind. Thanks a lot.
P.S. I have submitted another pull request. 
https://github.com/pnp/powerplatform-samples/pull/47

**Pull request merged**
