### PR TITLE
Responsive Canvas Template

### PR DESCRIPTION
**Pull request by shaheerahmadch**
- [ ] Bug fix?
- [x] New sample?
- [ ] Related issues: fixes #X, partially #Y, mentioned in #Z
- [ ] Needs API permissions?
- [ ] Has other prerequisites? (E.g. requires a list, document library, etc.)

## What's in this Pull Request?

Discover a seamless messaging experience with our responsive canvas app. Enjoy a familiar interface with modern convenience, making communication a breeze.

## Checklist

- [x] My pull request affects only ONE sample.
- [x] I have updated the README file.
- [x] My README has at least one static high-resolution screenshot (i.e. not a GIF)
- [x] My README contains complete setup instructions, including pre-requisites and permissions required

### CODE REVIEW

**Comment by aprildunnam** [comment]
Thanks for the sample @shaheerahmadch .  I tested it, however, it is not responsive.  It looks like the app in the solution had scale to fit enabled so it's not behaving responsively.  Can you please update your solution?

**Comment by shaheerahmadch** [comment]
Sure. I'll update it in my free time and will let you know @aprildunnam

**Comment by shaheerahmadch** [comment]
I have updated the source code and solution after disabling the "Scale to Fit". Thank you @aprildunnam for brining out the issue. Appreciate it.

**Comment by shaheerahmadch** [comment]
@aprildunnam @Katerina-Chernevskaya

**Comment by shaheerahmadch** [comment]
Updated the branch. FYI @aprildunnam  @Katerina-Chernevskaya

**Comment by Katerina-Chernevskaya** [comment]
Hi @shaheerahmadch 

Thank you for your work!
During the app validation, I was blocked from creating a new contact. It seems that there is no Last Name field on the form, but this is a required field in the Dataverse table.
image
Could you please check and resolve it?

Thank you!

Katerina Ch.

**Comment by shaheerahmadch** [comment]
@Katerina-Chernevskaya Fixed the issues. Thanks

**Review by Katerina-Chernevskaya — APPROVED** [review]
Hi @shaheerahmadch ,

Thank you for your contribution! I've updated the Readme file according to the template, created sample.json, and packed the solution.
The solution has one minor issue - when you try to open a created contact it is loading and do not show up. Please fix it and submit the update. 
The main functionality of responsive design works.

Thanks again!

Regards,
Katerina Ch.

**Pull request merged**
