### PR TITLE
Initial build

### PR DESCRIPTION
**Pull request by StuartBaxter-MVP**
> By submitting this pull request, you agree to the [contribution guidelines](https://github.com/pnp/powerplatform-samples/blob/main/CONTRIBUTING.md)

> If you aren't familiar with how to contribute to open-source repositories using GitHub, or if you find the instructions on this page confusing, sign up for one of our [Sharing is Caring](https://pnp.github.io/sharing-is-caring/#pnp-sic-events) events. It's completely free, and we'll guide you through the process.

> To submit a pull request with multiple authors, make sure that at least one commit is a co-authored commit by adding a `Co-authored-by:` trailer to the commit's message. E.g.: `Co-authored-by: name <name@example.com>`

> Put an `x` in all the items that apply (`[x]`, without spaces), make notes next to any that haven't been addressed.

- [ ] Bug fix?
- [x] New sample?
- [ ] Related issues: fixes #X, partially #Y, mentioned in #Z
- [ ] Needs API permissions?
- [ ] Has other prerequisites? (E.g. requires a list, document library, etc.)

## What's in this Pull Request?

Initial submission of the Dataverse security toolkit

## Checklist

> This checklist is mostly useful as a reminder of small things that can easily be forgotten – it is meant as a helpful tool rather than hoops to jump through.
>
> Put an `x` in all the items that apply ([x], no spaces), make notes next to any that haven't been addressed.

- [x] My pull request affects only ONE sample.
- [x] I have updated the README file.
- [x] My README has at least one static high-resolution screenshot (i.e. not a GIF)
- [x] My README contains complete setup instructions, including pre-requisites and permissions required

### CODE REVIEW

**Comment by StuartBaxter-MVP** [comment]
This is my first sample, so please reach out if I need to change anything

**Review by Laskewitz — APPROVED** [review]
Thanks @StuartBaxter-MVP - great submission. Looks like a great solution for people.

I fixed some things like the readme, regenerated the solution, and imported it in my environment. 

There was a little error (see screenshot below) when I opened the app at the top, but nothing major to hold this one back. If you want, you can create a new PR to fix the error and I'll look at that as well. 

image

Thanks for your hard work!

**Comment by StuartBaxter-MVP** [comment]
I'll get that fixed this weekend

thanks Stuart

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by StuartBaxter-MVP** [comment]
Hi Daniel,

Apologies for the delay in fixing this, I've uploaded a new version and another sample (PR #44)

thanks Stuart

Sent from Proton Mail mobile

-------- Original Message --------

**Pull request merged**
