### PR TITLE
Patch Tuesday

### PR DESCRIPTION
**Pull request by korebreach**
- [ ] Bug fix?
- [X] New sample?
- [ ] Related issues: fixes #X, partially #Y, mentioned in #Z
- [ ] Needs API permissions?
- [ ] Has other prerequisites? (E.g. requires a list, document library, etc.)

## What's in this Pull Request?
Methods for calculating Microsoft Patch Tuesday values. Sample includes (1) an instant cloud flow that will provide a timestamp for Patch Tuesday in the current month, (2) a scheduled cloud flow to run every Tuesday that will determine if it is running on Patch Tuesday, (3) a canvas app that will return a timestamp for Patch Tueday when selecting an arbitrary date, and (4) an instant cloud flow, to support the arbitrary date app

- [X] My pull request affects only ONE sample.
- [X] I have updated the README file.
- [X] My README has at least one static high-resolution screenshot (i.e. not a GIF)
- [X] My README contains complete setup instructions, including pre-requisites and permissions required

### CODE REVIEW

**Comment by Katerina-Chernevskaya** [comment]
Hello @korebreach ,

Thank you for your submission! We value your time and contribution.
To move forward with the review and merging of your pull request, we kindly request that you update your PR in accordance with the [Contribution Guidelines](https://github.com/pnp/powerplatform-samples/blob/main/CONTRIBUTING.md). Please ensure that the README file is updated following the [provided template](https://github.com/pnp/powerplatform-samples/blob/main/templates/sample-template/README.md), and add the source code as [instructed](https://github.com/pnp/powerapps-samples/wiki/How-to-submit-a-Power-App-sample#create-the-folder-structure).

Thank you!

Regards,
Katerina Chernevskaya

**Comment by korebreach** [comment]
Thanks Katerina.  I have made the requested changes.  Please let me know if there is anything else I need to do for this pull request.

**Comment by Katerina-Chernevskaya** [comment]
Hi @korebreach 

Thank you for the update! I successfully compil the solution from the source code. However I received an error in the Canvas App when tried to change the date: 
image

Could you please check this and update the source code?

Thank you!

Regards,
Katerina Chernevskaya

**Comment by korebreach** [comment]
Hi Katerina.  Hopefully "3rd times a charm" :)  For some reason, the app became disconnected from the flow.  I've remade the connection and reloaded the sourcecode.  Also, in a careful reading of the instructions, I see I was not supposed to include the solution.zip file.  I've removed that, which removed the solution directory since it was empty.  I've also replaced the assets/PatchTuesdayArbitraryDate.png file, which appeared to be corrupted.

**Comment by korebreach** [comment]
Also... my soluton.zip file (that you'll be generating) was actually named PatchTuesday.zip.  Since you'll be naming it solution.zip, I fixed the link in the README.md file to point to solution.zip.

**Comment by Katerina-Chernevskaya** [comment]
Hi @korebreach,
Thank you for your support!
But I still experience the same issue with disconnected flow:
image
Could you please check one more time please, as well as please test the process of import the solution to another environment and check if the app works. Did you create the flow from the solution or just added it?

Thank you in advance!

Katerina Ch.

**Comment by korebreach** [comment]
This is strange.  The flow was added to a solution via the Power Apps Maker Portal.  When I go into the solution and preview the app, it works well.  I'll try importing the solution from GitHub and see if I have the same problem you're having.

**Comment by korebreach** [comment]
Hi Katerina.  I checked the whole solution again and found that I had forgot to publish (only saved) the most recent (fixed) version.  I re-exported the solution after fixing this.  However, I wanted to test re-packing it to make sure it was working after getting to GitHub.  When I try repacking it, I get an error that it can't find the sourcecode/other/customizations.xml file.  There is no "other" directory under the sourcecode directory, and I don't believe there should be for my solution.  Looking at other solutions uploaded to the samples repository, some have the "other" directory and some don't.  Seems like a benign error, but please let me know if it's something I need to worry about.

Otherwise, the solution is ready for your review again.

**Pull request merged**
