### PR TITLE
espiritu-branch to Main branch for Healthcare Chatbot

### PR DESCRIPTION
**Pull request by thepersonwho**
## Category
- [x] New sample?

## What's in this Pull Request?
- Added solution Healthcare Chatbot sample for Global AI Hackathon 2023

## Checklist

- [x] My pull request affects only ONE sample.
- [x] I have updated the README file.
- [x] My README has at least one static high-resolution screenshot (i.e. not a GIF)
- [x] My README contains complete setup instructions, including pre-requisites and permissions required

### CODE REVIEW

**Comment by Katerina-Chernevskaya** [comment]
Hello @thepersonwho ,

Thank you for your contribution! Your time and contribution are highly valued.

During the import the solution I had an issue with dependencies. Please check the log below:
`[{"SolutionValidationResultType":"Error","Message":"The following solution cannot be imported: HealthcareHackathonAISolution. Some dependencies are missing. The missing dependencies are : <MissingDependencies><MissingDependency><Required type=\"connectionreference\" displayName=\"hhp_sharedcommondataserviceforapps_a7589\" solution=\"Active\" id.connectionreferencelogicalname=\"hhp_sharedcommondataserviceforapps_a7589\" /><Dependent type=\"29\" displayName=\"Extract symptoms and suggest Doctor\" id=\"{94672084-1659-ee11-be6f-000d3a338c5d}\" /></MissingDependency><MissingDependency><Required type=\"connectionreference\" displayName=\"hhp_sharedcommondataserviceforapps_a7589\" solution=\"Active\" id.connectionreferencelogicalname=\"hhp_sharedcommondataserviceforapps_a7589\" /><Dependent type=\"29\" displayName=\"Check doctor's schedule\" id=\"{9da85dd8-f65b-ee11-be6f-000d3a338c5d}\" /></MissingDependency></MissingDependencies> , ProductUpdatesOnly : False","ErrorCode":-2147188707,"AdditionalInfo":null}]`

Could you please check your source code and update it to fix this error?

Additionally we kindly request you keep the folder name 'powerplatform-samples' unchanged.

Please also check the folder 'powerpages-portalfiles' and the file 'HealthcareHackathonAISolution.cdsproj'. If they are integral to the solution, could you please provide the installation steps for them in the README?

Make sure to update your branch to reflect the latest changes from the main branch.

Thank you!

Regards,
Katerina Chernevskaya

**Comment by thepersonwho** [comment]
Hi @Katerina-Chernevskaya, I updated the solution folder to include the missing dependency, a connection reference I forgot to add. The 'powerpages-portalfiles' and the file 'HealthcareHackathonAISolution.cdsproj' aren't really needed for the component to work, they were simply included from when I exported the solution. I can delete them if needed.

Also, when you mentioned that I should keep the folder name 'powerplatform-samples' unchanged, were you referring to my fork's name? I currently do not have any pull requests from the 'powerplatform-samples' repo.

Thanks,
@thepersonwho

**Comment by thepersonwho** [comment]
Hi @Katerina-Chernevskaya ,

I removed the 2 unused files from the sample folder and I renamed the fork to 'powerplatform-samples'. I also updated the solution zip file, so you shouldn't have any more problems importing it. 

Let me know if anything comes up.

Thanks,
@thepersonwho

**Review by Katerina-Chernevskaya — APPROVED** [review]
Hi @thepersonwho,

Thank you for your contribution!
I have made some changes in the README file: incorporated a HELP section, restructured the content to align with our template, and added information regarding AI Builder in the prerequisites section.

Great bot! Thank you!

Regards,
Katerina Chernevskaya

**Pull request merged**
